# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3MyZwz_jZf9S04rxf7qMOoM5WZkdRHm
"""



"""User will input (3age) find the oldest one

"""

age1 = int(input("enter Age 1:"))
age2 = int(input("enter Age 2:"))
age3 = int(input("enter Age 3:"))
if (age1 >= age2) and (age1 >= age3):
  oldest = 1
elif (age2 >= age1) and (age2 >= age3):
  oldest = 2
else:
  oldest = 3
print("oldest Age is ",oldest )

